#!/usr/bin/env bash
sudo apt install stow
for d in */ ; do
    stow $d
done

/usr/bin/python3 -m pip install pynvim typing_extensions

sudo apt install -y bat git-delta fzf neovim clang-format

if ! which delta; then
    wget https://github.com/dandavison/delta/releases/download/0.18.2/git-delta_0.18.2_amd64.deb && sudo dpkg -i git-delta_0.18.2_amd64.deb && rm git-delta_0.18.2_amd64.deb
fi


if ! which docker; then
    ./install_docker.sh
fi

if ! which bcompare; then
    ./install_bcompare.sh
fi
